name: back-dev

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: niti-dev
      POSTGRES_USER: devuser
      POSTGRES_HOST_AUTH_METHOD: trust # no password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U devuser -d niti-dev
      interval: 5s
      timeout: 5s
      retries: 10

  migrations:
    image: migrate/migrate
    restart: "no"
    depends_on:
      - postgres
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://devuser@postgres:5432/niti-dev?sslmode=disable",
        "up",
      ]
    volumes:
      - ./migrations:/migrations

volumes:
  postgres_data:
