name: back-dev

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: niti-dev
      POSTGRES_USER: devuser
      POSTGRES_HOST_AUTH_METHOD: trust # no password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d niti-dev"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrations:
    build: .
    entrypoint: ["./migrator"]
    command: ["-command=up"]
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    environment:
      POSTGRES_MIGRATIONS_PATH: file:///migrations
      POSTGRES_DSN: postgresql://devuser@postgres:5432/niti-dev?sslmode=disable
    env_file:
      - .env
    restart: "no"

volumes:
  postgres_data:
