# yaml-language-server: $schema=../../../configuration-schema.json
package: genapi
output: generated.go
generate:
  models: true
  gin-server: true
  strict-server: true
output-options:
  skip-prune: true
