<<<<<<<< HEAD:backend/pkg/publicapi/config.yaml
package: publicapi
========
package: openapi
>>>>>>>> fa0884c (Remove privateapi):backend/pkg/openapi/config.yaml
output: generated.go
generate:
  models: true
  gin-server: true
  strict-server: true
output-options:
  skip-prune: true
