# yaml-language-server: $schema=../../../configuration-schema.json
package: api
output: generated.go
generate:
  models: true
  chi-server: true
  strict-server: true
output-options:
  skip-prune: true
